install:
  - ps: | 
      Install-Module Disposable -Force
      Install-Module Error -Force
      Install-Module Pester -Force
      Install-Module PoshRSJob -Force

build: false

test_script:
  - ps: Import-Module ..\Jojoba -Force
  - ps: $res = Invoke-Pester -Path "." -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  