install:
  - ps: | 
      Install-Module Disposable -Force -AllowClobber
      Install-Module Error -Force -AllowClobber
      Install-Module Pester -Force -AllowClobber
      Install-Module PoshRSJob -Force -AllowClobber

build: false

test_script:
  - ps: |
      $env:PSModulePath = "$((Get-Item .).FullName)\;$($env:PSModulePath)"
      $res = Invoke-Pester -Path "." -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
      if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - pwsh: |
      $env:PSModulePath = "$((Get-Item .).FullName)\;$($env:PSModulePath)"
      $res = Invoke-Pester -Path "." -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
      if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  